# product.yaml

status:
  # Magento Status Code 1 (Enabled)
  1:
    woo: publish
    medusa: published
  # Magento Status Code 2 (Disabled)
  2:
    woo: draft
    medusa: draft

type_id:
  # Magento Type 'simple'
  simple:
    woo: simple
    medusa: default
  # Magento Type 'configurable'
  configurable:
    woo: variable
    medusa: default
  grouped:
    woo: grouped
    medusa: default
  virtual:
    woo: simple
    medusa: default
  downloadable:
    woo: simple
    medusa: default

visibility:
  # 4: Hiển thị đầy đủ (Phổ biến nhất)
  4:
    woo: visible
    medusa: published

  # 3: Chỉ Catalog (Thường được xử lý như hiển thị đầy đủ trừ khi có logic tùy chỉnh)
  3:
    woo: visible
    medusa: published

  # 2: Chỉ Search (Gần như ẩn, trừ khi người dùng biết tìm kiếm)
  2:
    woo: visible              # hidden
    medusa: draft

  # 1: Không hiển thị riêng lẻ (Dùng cho sản phẩm con)
  1:
    woo: visible              # hidden
    medusa: draft