connectors:
  magento:
    args:
      base_url:
      token:
    class: MagentoConnector
    labels:
      base_url: Base URL
      token: Access Token
  woo:
    args:
      base_url:
      wq_password:
      wq_username:
    class: WooCommerceConnector
    labels:
      base_url: Base URL
      wq_password: WordPress Password
      wq_username: WordPress Username
